# transaction-bff-docker.yml
transacoes:
  events: 'coffeeandit-sse1'
  duration: 2

limites:
  url: http://limites-svc:8081  # Nome do container do serviço de limites

transaction:
  url: http://transaction-svc:8082  # Nome do container do serviço de transação

spring:
  data:
    redis:
      host: redis-container
      port: 6379
      password:
      timeout: 60000ms
  kafka:
    producer:
      client-id: transaction
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: transaction
    bootstrap-server: kafka:9092
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 3000
resilience4j:
  circuitbreaker:
    instances:
      limiteCircuitBreaker:
        failure-rate-threshold: 60
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
      countBasedCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        slow-call-rate-threshold: 65
        slow-call-duration-threshold: 2s
      timeBasedCircuitBreaker:
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 3
        failure-rate-threshold: 70
        wait-duration-in-open-state: 10s
        writable-stack-trace-enabled: false
  retry:
    instances:
      limiteRetry:
        max-attempts: 3
        wait-duration: 500ms
